lab50:
  files:
    - !exclude "*"
    - !include "hello.c"
    - !include "test.txt"

check50: 
  files:
    - !exclude "*"
    - !require hello.c
    - !require "test.txt"

submit50:
  files:
    - !exclude "*"
    - !require hello.c
