check50:
  files:
    - !exclude "*"
    - !require "aliejus.c"
    - !require "U1.txt"
    - !require "U1rez.txt"

lab50:
  files:
    - !exclude "*"
    - !include "aliejus.c"
    - !include "U1.txt"
    - !include "U1rez.txt"

submit50:
  files:
    - !exclude "*"
    - !require "aliejus.c"
    - !include "U1.txt"
    - !include "U1rez.txt"
